PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX UBERON: <http://purl.obolibrary.org/obo/UBERON_>

SELECT DISTINCT ?o ?s ?olabel ?slabel (str(?o_mba) as ?user_olabel) (str(?s_mba) as ?user_slabel)
WHERE{
    ?s_mba rdfs:subClassOf ?s .
    ?s_mba rdfs:subClassOf ?restriction.
    ?restriction owl:onProperty <http://purl.obolibrary.org/obo/BFO_0000050> .
    ?restriction owl:someValuesFrom ?o_mba .
    ?o_mba rdfs:subClassOf ?o .
    ?s rdfs:label ?slabel .
    ?o rdfs:label ?olabel .

    FILTER (isIRI(?o) && STRSTARTS(STR(?o), "http://purl.obolibrary.org/obo/UBERON_"))
    FILTER (isIRI(?s) && STRSTARTS(STR(?s), "http://purl.obolibrary.org/obo/UBERON_"))
    FILTER (?o != ?s)
    FILTER (STRSTARTS(STR(?s_mba), "http://purl.obolibrary.org/obo/MBA_") || STRSTARTS(STR(?s_mba), "http://purl.obolibrary.org/obo/DMBA_"))
}